### ISSUE TITLE
lightline.vim: Could not load colorscheme highlight.

### ISSUE THREAD

**Issue by maxdzyubak** [igemnace/highlight.vim#2]
Hi, Ian. Thanks for you very cool theme. But my plugin lightline.vim not visible theme highlight. 

- OS: masOS Ventura 13.2
- Terminal: iTerm2
- Vim version: 9.0.981
- Install: PlugInstall

[my-install-plugins](https://capture.dropbox.com/Nvo1Irg1YzCoI3wR)
[error](https://capture.dropbox.com/u9qW96EDOw4QiBOA)
[plugin lightline](https://capture.dropbox.com/YGXMLQ1mGc1ek8Nu)

**Comment by igemnace** [comment]
Hi! That's because lightline colorschemes are not the same as Vim colorschemes -- a lightline colorscheme is essentially a variable with contents that lightline understands: https://github.com/itchyny/lightline.vim/blob/b1e91b41f5028d65fa3d31a425ff21591d5d957f/autoload/lightline.vim#L193-L195

This is in line with its README: lightline colorschemes are different from editor colorschemes: https://github.com/itchyny/lightline.vim#colorscheme-configuration

I don't use lightline ([I configure my own statusline](https://github.com/igemnace/vim-config/blob/bd49d5d7eaccf79d0331887e36541ecda97c424c/cfg/vimrc#L58-L74)). I'll likely take a look into it, but know that I have less motivation to add support for it (so no guarantees), and I wouldn't be able to dogfood it anyhow. PRs welcome in this department!

**Comment by maxdzyubak** [comment]
Hi! Thanks for you answer. Good luck.
